feat: remove necessity of wrapping navigators into container
react-navigation/navigation-ex pull request #21
Opened 2019-07-21 19:40 UTC by osdnk

2019-07-21 21:16 UTC, brentvatne commented
the motivation for explicit containers was two-fold:
1) people were rendering navigators in nested components without realizing the implications of doing this - it would basically create a new navigation container with a navigation subtree that was disconnected from the parent, leading to some confusing behavior for people. in the new design on this repo this wouldn't be an issue because rendering navigators this way is one of the main motivations behind the design.
2) on web/native we want to use different navigation containers: https://github.com/react-navigation/web/blob/master/src/createBrowserApp.js and https://github.com/react-navigation/native/blob/master/src/createAppContainer.js. so, if we provide a default container then we either have to bias towards one of them or include both and pick automatically depending on platform.

2019-07-21 22:59 UTC, osdnk commented
1. It’s not an issue
2. Container is so far very small and designed for mobile. Assuming that most of react navigation users are focused on mobile and a lot of them does not need deeplinking etc, can’t we assume it will cover most of cases?

2019-07-22 10:29 UTC, satya164 commented
The container also handles hardware back button on mobile which I think all apps which support Android need to handle. And for webs, I think history integration is something people will want to have. So users would need to wrap their code in container still.

Though we can still wrap by default with the base container without any additional functionality by default. When users use another container, that'll work fine. The only problem is that by not making it explicit, users may not realize that they need to do it to handle back button etc.

I don't have any strong opinion on this. So lemme know what you prefer.

2019-07-22 16:11 UTC, osdnk commented
@brentvatne it's up to you

2019-07-23 15:20 UTC, satya164 requested changes

2019-07-23 15:20 UTC, satya164 commented on src/__tests__/NavigationContainer.test.tsx
> +it('throws when performTransaction is accessed without a container but inside navigator', () => {
doesn't throw?

2019-07-23 15:20 UTC, satya164 commented on src/__tests__/NavigationContainer.test.tsx
> +  render(element).update(element);
nit: new line before xd

2019-07-23 15:20 UTC, satya164 commented on src/createNavigator.tsx
> +import { NavigationContainer } from './index';
move the import to `NavigationContainer` file like above to avoid circular dep

2019-07-23 15:20 UTC, satya164 commented on src/createNavigator.tsx
> +        if (getState() === null) {
nit: new line before xd

2019-07-23 15:20 UTC, satya164 commented on src/createNavigator.tsx
> +import { NavigationContainer } from './index';
nit: unrelated, but can you move the types import to bottom xd

2019-07-27 13:47 UTC, osdnk commented
drob it

2019-07-27 13:47 UTC, closed without merging