feat: accept router to be a function
react-navigation/navigation-ex pull request #22
Opened 2019-07-21 20:57 UTC by osdnk

todo: add tests

2019-07-22 10:32 UTC, satya164 commented
Can you drop the commit regarding `setOptions` and rebase against master so it's easier to review?

2019-07-22 16:13 UTC, osdnk commented
@satya164 My changes are built on thew top of yours. If you're force-pushed commit with another hash, it might imply problems. I can do it after merging your PR.

2019-07-22 19:19 UTC, satya164 requested changes

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
> +    typeof router === 'function' ? router(options) : router
I think it's better to just always make it a function rather than accepting both object and function

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
> +    typeof router === 'function' ? router(options) : router
I think we shouldn't pass things like `children` to the router. It'll be problematic if someone writing a custom router uses children.

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
>        initialRouteName,
Since we now pass `initialRouteName` as an option, we could remove it from here

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
>        initialParamsList,
Let's rename this to `routeParamList`, since it's not really initial as it changes when children change.

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
> +  const { current: currentRouter } = React.useRef<Router<any>>(
Since there's always going to be one router, I think no need to say `currentRouter`, `router` looks nicer 😛

2019-07-22 19:19 UTC, satya164 commented on src/useNavigationBuilder.tsx
> +  Options extends DefualtOptions = DefualtOptions
`RouterOptions`

2019-07-22 19:30 UTC, satya164 commented on src/types.tsx
> +export type DefualtOptions = {
`RouterDefaultOptions`

2019-07-23 20:57 UTC, satya164 commented on src/types.tsx
> -   * @param options.initialParamsList Object containing initial params for each route.
small typo

2019-07-23 20:57 UTC, satya164 commented on src/types.tsx
> -   * @param options.initialParamsList Object containing initial params for each route.
small typo

2019-07-23 20:57 UTC, satya164 commented on src/types.tsx
> +export type RouterHelper<
maybe `RouterCreator`?

2019-07-23 20:57 UTC, satya164 commented on src/types.tsx
> +  children: React.ReactNode;
router doesn't use children no?

2019-07-23 21:21 UTC, satya164 approved these changes

2019-07-23 21:21 UTC, merged