fix: screens integration on Android
react-navigation/navigation-ex pull request #294
Opened 2020-01-24 16:28 UTC by osdnk

2020-01-27 14:35 UTC, satya164 requested changes

2020-01-27 14:35 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +  const listenerRef = React.useRef<string>();
You don't need a ref. Move it to the callback to `useEffect`, then you won't need to set it to undefined either.

2020-01-27 14:35 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +  const valueListenerCallback = React.useCallback(
You can also move the callback to inside `useEffect`. It'll remove the need for adding `useCallback`.

2020-01-27 14:35 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +      if (newIsUnderEpsilon !== pointerEvents) {
You don't need to check, afaik React will skip the update if the value is the same (only for `useState` hook). BTW it's better to use the updater callback to check previous state.

2020-01-27 14:35 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +      const newIsUnderEpsilon = value <= EPSILON ? 'box-none' : 'none';
Maybe different variable name?

2020-01-27 14:36 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +      listenerRef.current = scene.progress.next.addListener(
Use optional chaning

```suggestion
      listenerRef.current = scene.progress.next?.addListener(
```

2020-01-27 14:37 UTC, satya164 commented on packages/stack/src/views/Stack/CardContainer.tsx
> +        scene.progress.next.removeListener(listenerRef.current);
Use optional chaning

```suggestion
        scene.progress.next?.removeListener(listenerRef.current);
```

2020-01-27 16:47 UTC, satya164 approved these changes

2020-01-27 16:48 UTC, merged

2020-01-27 16:49 UTC, satya164 approved these changes
Thanks a ton for this contribution!
I'm extremely thankful for these changes and proud of these great lines of code!

I strongly encourage you for further development and can't wait for the next great changes! Do not give up doing a good job!

😍

2020-02-06 07:40 UTC, kopax commented
Hello, thanks for your contribution, unfortunatly, this break my migration to v5 final :

https://github.com/react-navigation/react-navigation/issues/363

error is in there: https://github.com/react-navigation/react-navigation/blob/250fa9abc2174e39b80fe976428044ab4869abc1/packages/stack/src/views/Stack/CardStack.tsx#L42 

```
nst maybeExpoVersion = global.Expo?.Constants.manifest.sdkVersion.split(
  '.'
)[0];
```

All my test now are failing with:

```
    TypeError: Cannot read property 'split' of undefined

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:42:26)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:8:1)
```

not sure how to do now, should I mock this ? It could break all my test environment... Thanks!

2020-02-06 18:04 UTC, kopax commented
Without 

```
const maybeExpoVersion = global.Expo?.Constants.manifest.sdkVersion.split(
  '.'
)[0];
```

My test can go through.  Could we please make this more permissive? No reason to let this break our test environment, this is regression.